---
"pathogen_filter_name": "MERS-CoV"
"tables_to_stack": ["parameters", "models"]
"continuation_config":
    "continuation_table": "articles"
    "id_col": "record_id"
    "cov_id_col": "article_covidenceid"
    "continuation_col": "article_continuation"
    "extractor_col": "extractor_name"
    "incomplete_col": "pathogen_epidemiology_review_complete"
    "notes_cols": ["article_notes", "qa_notes"]
"target_filepath": "redcap_data/table_target.csv"
"mapping_filepath": "redcap_data/nipah/mapping_table.csv"
"table_filepaths":
    "all_data": "mers_raw_data.csv"
"linked_row_col_names":
    "models": "model_linked"
    "parameters": "parameter_linked"
"incomplete_col_names":
    "articles": "pathogen_epidemiology_review_complete"
"incomplete_col_key": "Incomplete"
"target_table_names": ["articles", "models", "parameters"]
"data_table_names": ["models", "parameters"]
"pk_col_names":
    "models": "access_model_id"
    "parameters": "access_param_id"
date_cols_to_split:
    "parameters": ["Population_study_start", "Population_study_end"]
"uuid_col_names":
    "articles": "ID"
    "parameters": "Parameter_data_ID"
    "models": "Model_data_ID"
"article_cols_to_add_end": ["Pathogen", "ID"]
"article_cols_to_add_start": [ "Covidence_ID", "Name_data_entry"]
"article_id": "Article_ID"
---

