---
"pathogen_filter_name": "Nipah virus"
"tables_to_stack": ["parameters", "models", "outbreaks"]
"target_filepath": "redcap_data/table_target.csv"
"mapping_filepath": "redcap_data/nipah/mapping_table.csv"
orderly_download_depencency: false
"table_filepaths":
    "all_data": "redcap_data/nipah/raw_data/nipah_raw_data.csv"
"linked_row_col_names":
    "models": "model_linked"
    "outbreaks": "outbreak_linked"
    "parameters": "parameter_linked"
"incomplete_col_names":
    "articles": "pathogen_epidemiology_review_complete"
"target_table_names": ["articles", "models", "outbreaks", "parameters"]
"data_table_names": ["models", "outbreaks", "parameters"]
"pk_col_names":
    "outbreaks": ["access_outbreak_id", "Outbreak_ID"]
    "models": "access_model_id"
    "parameters": "access_param_id"
date_cols_to_split:
    "outbreaks": ["Outbreak_start", "Outbreak_end"]
    "parameters": ["Population_study_start", "Population_study_end"]
"uuid_col_names":
    "articles": "ID"
    "outbreaks": "Outbreak_data_ID"
    "parameters": "Parameter_data_ID"
    "models": "Model_data_ID"
article_cols_to_add: ["Pathogen", "Covidence_ID", "Name_data_entry", "ID"]
---

